In [1]:
data = open('data.txt').read().splitlines()

### Data formating

In [2]:
coords = []
for line in data:
    line_split = line.split(' -> ')
    xy = []
    for coord in line_split:
        xy.append(tuple(map(int, coord.split(','))))
    coords.append(xy)

look at the data

Consider only horizontal and vertical lines. Remove all points where $x_1$ and $x_2$ is not the same or $y_1$ and $y_2$ is not the same

In [4]:
test_coords = []
for coord in coords:
    if coord[0][0] == coord[1][0] or coord[0][1] == coord[1][1]:
        test_coords.append(coord)

look at the test coordinates

In [5]:
test_coords

[[(0, 9), (5, 9)],
 [(9, 4), (3, 4)],
 [(2, 2), (2, 1)],
 [(7, 0), (7, 4)],
 [(0, 9), (2, 9)],
 [(3, 4), (1, 4)]]

In [6]:
xmax = 0
ymax = 0

for coord in test_coords:
    x1, y1 = coord[0]
    x2, y2 = coord[1]
    x = max([x1,x2])
    y = max([y1,y2])
    
    if x > xmax:
        xmax = x
    if y > ymax:
        ymax = y

In [7]:
import numpy as np

create a diagram

In [29]:
diagram = np.zeros((10,10))

for coord in coords:
    x1, y1 = coord[0]
    x2, y2 = coord[1]
    
    if x1 == x2 and y1 != y2:
        if y1 > y2:
            for y in range(y1,y2-1,-1):
                diagram[y,x1] += 1
        elif y1 < y2:
            for y in range(y1,y2+1):
                diagram[y,x1] += 1
                
    if x1 != x2 and y1 == y2:
        if x1 > x2:
            for x in range(x1,x2-1,-1):
                diagram[y1,x] += 1
        elif x1 < x2:
            for x in range(x1,x2+1):
                diagram[y1,x] += 1
            
    if x1 == x2 and y1 == y2:
        diagram[y1,x1] += 1

look at diagram

In [31]:
diagram

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 1., 1., 1., 0., 0., 0., 0.]])

determine the number of points where at least two lines overlap

In [17]:
num = 0
for row in (diagram > 1):
    for col in row:
        if col == True:
            num += 1

In [18]:
num

5

# Part 2

In [61]:
diagram = np.zeros((10,10))

for coord in coords:
    x1, y1 = coord[0]
    x2, y2 = coord[1]
    
    if x1 == x2 and y1 != y2:
        if y1 > y2:
            for y in range(y1,y2-1,-1):
                diagram[y,x1] += 1
        elif y1 < y2:
            for y in range(y1,y2+1):
                diagram[y,x1] += 1
                
    if x1 != x2 and y1 == y2:
        if x1 > x2:
            for x in range(x1,x2-1,-1):
                diagram[y1,x] += 1
        elif x1 < x2:
            for x in range(x1,x2+1):
                diagram[y1,x] += 1
            
    if x1 == x2 and y1 == y2:
        diagram[y1,x1] += 1
        
    # check diagonal
    xlen = abs(x1-x2)
    ylen = abs(y1-y2)
    if xlen > 0 and ylen > 0:
        angle = np.around(np.arctan(ylen/xlen)*180/np.pi)
        if angle == 45.0:
            xlist = [x1,x2]
            ylist = [y1,y2]
            xlist.sort()
            ylist.sort()

            _t = xlist[1] - xlist[0]
            
            for i in range(_t+1):
                diagram[ylist[0] + i,xlist[0] + i] += 1

In [59]:
diagram

array([[2., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 2., 1., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 3., 0., 1., 1., 0., 1., 0., 0.],
       [0., 0., 0., 2., 0., 1., 1., 1., 0., 0.],
       [0., 1., 1., 2., 3., 1., 2., 3., 1., 1.],
       [0., 0., 0., 0., 0., 2., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [2., 2., 2., 1., 1., 1., 0., 0., 0., 0.]])

In [35]:
a = [1,3,2]
a.sort()
a

[1, 2, 3]

In [27]:
diagram

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 1., 2., 1., 1., 1., 2., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 1., 1., 1., 0., 0., 0., 0.]])